In [1]:
import easygui
import os
import cv2
faceCascade = cv2.CascadeClassifier("face.xml")
try:
    name = easygui.enterbox()
except:
    name = "random"
try:
    os.mkdir("datasetf")
except:
    pass
try:
    os.mkdir("datasetf"+f"\\"+name)
except:
    pass
video_capture = cv2.VideoCapture(0)
new_path = "datasetf\\"+name

In [2]:
name

'simran'

In [ ]:
import os
os.mkdir("datasetf")

In [ ]:
pip install easygui

In [36]:
name

'simran'

In [3]:
i = 0
while True:
    ret, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=5, minSize=(100, 100), flags=cv2.CASCADE_SCALE_IMAGE)
    for (x, y, w, h) in faces:
        i=i+1
        cv2.imwrite(new_path+"\\"+name +'_'+ str(i) + ".jpg", gray[y:y+h,x:x+w])
        print("file_saved")
        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        print(frame)
        print(i)
    try:
        cv2.imshow('Video', frame)
    except:
        continue
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    if i+1>200:
        break
video_capture.release()
cv2.destroyAllWindows()

file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
1
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
2
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]


file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
23
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
24
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]

file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
46
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
47
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]

file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
70
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
71
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]

file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
93
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
94
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]

file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
117
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
118
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 

file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
141
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
142
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 

file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
164
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
165
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 

file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
187
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
188
file_saved
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 

In [48]:
import os
os.remove("datasetf\\weapon_possesion.json")

In [4]:
import cv2
import os
from PIL import Image 
import pickle
import numpy as np
face_dict = {}
def get_images_and_labels(path):
    global face_dict
    names=os.listdir("datasetf")
    image_paths=[]
    new_path="datasetf"
    for name in names:
        image_paths.append([os.path.join(new_path+"\\"+name, f) for f in os.listdir(new_path+"\\"+name)])
    print(image_paths)
 # images will contains face images
    images = []
 # labels will contains the label that is assigned to the image
    labels = []
    nbr = 0
    i = 0
    j = 0
    k = 0
    for name in names:
        for image_path in image_paths[j]:
             # Read the image and convert to grayscale
            image_pil = Image.open(image_path).convert('L')
             # Convert the image format into numpy array
            image = np.array(image_pil, 'uint8')
            face_dict[j] = name
            print(face_dict)
            #nbr=int(''.join(str(ord(c)) for c in nbr))
            print(image_path)
             # Detect the face in the image
            faceCascade = cv2.CascadeClassifier('face.xml')
            faces = faceCascade.detectMultiScale(image)
             # If face is detected, append the face to images and the label to labels
            for (x, y, w, h) in faces:
                images.append(image[y: y + h, x: x + w])
                labels.append(j)
                cv2.imshow("Adding faces to traning set...", image[y: y + h, x: x + w])
                cv2.waitKey(10)
            i = i+1
        j = j+1
    return images,labels

def save_obj(obj, name ):
    with open(name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

#file_rename(path,names)
recognizer = cv2.face.LBPHFaceRecognizer_create()
recognizer.read('trainer\\trainer.yml')
images, labels = get_images_and_labels('datasetf\\random')
#cv2.imshow('test',images[0])
#cv2.waitKey(1)
save_obj(face_dict,"trainer\\trained_faces")
recognizer.train(images, np.array(labels))
recognizer.save('trainer\\trainer.yml')
cv2.destroyAllWindows()

[['datasetf\\raju\\raju_1.jpg', 'datasetf\\raju\\raju_10.jpg', 'datasetf\\raju\\raju_100.jpg', 'datasetf\\raju\\raju_101.jpg', 'datasetf\\raju\\raju_102.jpg', 'datasetf\\raju\\raju_103.jpg', 'datasetf\\raju\\raju_104.jpg', 'datasetf\\raju\\raju_105.jpg', 'datasetf\\raju\\raju_106.jpg', 'datasetf\\raju\\raju_107.jpg', 'datasetf\\raju\\raju_108.jpg', 'datasetf\\raju\\raju_109.jpg', 'datasetf\\raju\\raju_11.jpg', 'datasetf\\raju\\raju_110.jpg', 'datasetf\\raju\\raju_111.jpg', 'datasetf\\raju\\raju_112.jpg', 'datasetf\\raju\\raju_113.jpg', 'datasetf\\raju\\raju_114.jpg', 'datasetf\\raju\\raju_115.jpg', 'datasetf\\raju\\raju_116.jpg', 'datasetf\\raju\\raju_117.jpg', 'datasetf\\raju\\raju_118.jpg', 'datasetf\\raju\\raju_119.jpg', 'datasetf\\raju\\raju_12.jpg', 'datasetf\\raju\\raju_120.jpg', 'datasetf\\raju\\raju_121.jpg', 'datasetf\\raju\\raju_122.jpg', 'datasetf\\raju\\raju_123.jpg', 'datasetf\\raju\\raju_124.jpg', 'datasetf\\raju\\raju_125.jpg', 'datasetf\\raju\\raju_126.jpg', 'datasetf\\

{0: 'raju'}
datasetf\raju\raju_1.jpg
{0: 'raju'}
datasetf\raju\raju_10.jpg
{0: 'raju'}
datasetf\raju\raju_100.jpg
{0: 'raju'}
datasetf\raju\raju_101.jpg
{0: 'raju'}
datasetf\raju\raju_102.jpg
{0: 'raju'}
datasetf\raju\raju_103.jpg
{0: 'raju'}
datasetf\raju\raju_104.jpg
{0: 'raju'}
datasetf\raju\raju_105.jpg
{0: 'raju'}
datasetf\raju\raju_106.jpg
{0: 'raju'}
datasetf\raju\raju_107.jpg
{0: 'raju'}
datasetf\raju\raju_108.jpg
{0: 'raju'}
datasetf\raju\raju_109.jpg
{0: 'raju'}
datasetf\raju\raju_11.jpg
{0: 'raju'}
datasetf\raju\raju_110.jpg
{0: 'raju'}
datasetf\raju\raju_111.jpg
{0: 'raju'}
datasetf\raju\raju_112.jpg
{0: 'raju'}
datasetf\raju\raju_113.jpg
{0: 'raju'}
datasetf\raju\raju_114.jpg
{0: 'raju'}
datasetf\raju\raju_115.jpg
{0: 'raju'}
datasetf\raju\raju_116.jpg
{0: 'raju'}
datasetf\raju\raju_117.jpg
{0: 'raju'}
datasetf\raju\raju_118.jpg
{0: 'raju'}
datasetf\raju\raju_119.jpg
{0: 'raju'}
datasetf\raju\raju_12.jpg
{0: 'raju'}
datasetf\raju\raju_120.jpg
{0: 'raju'}
datasetf\raju\raju

{0: 'raju', 1: 'simran'}
datasetf\simran\simran_107.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_108.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_109.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_11.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_110.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_111.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_112.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_113.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_114.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_115.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_116.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_117.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_118.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_119.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_12.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_120.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_121.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_12

{0: 'raju', 1: 'simran'}
datasetf\simran\simran_60.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_61.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_62.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_63.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_64.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_65.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_66.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_67.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_68.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_69.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_7.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_70.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_71.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_72.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_73.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_74.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_75.jpg
{0: 'raju', 1: 'simran'}
datasetf\simran\simran_76.jpg
{0: 'raju',

{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_79.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_8.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_80.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_81.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_82.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_83.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_84.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_85.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_86.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_87.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_88.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_89.jpg
{0: 'raju', 1: 'simran', 2: 'simranray'}
datasetf\simranray\simranray_9.jpg
{

{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_84.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_85.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_86.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_87.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_88.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_89.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_9.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_90.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_91.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_92.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_93.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi\sohi_94.jpg
{0: 'raju', 1: 'simran', 2: 'simranray', 3: 'sohi'}
datasetf\sohi

# Face Prediction

In [5]:
import cv2
import pickle
recognizer = cv2.face.LBPHFaceRecognizer_create()
recognizer.read('trainer\\trainer.yml')
cascadePath = "face.xml"
faceCascade = cv2.CascadeClassifier(cascadePath)
nbr_predicted, conf=0,0
with open("trainer\\trained_faces.pkl",'rb') as f:
    face_dict = pickle.load(f)
# face_dict=load_obj("trainer\\trained_faces")
cam = cv2.VideoCapture(0)
pre_detect = 0
while True:
    ret, im = cam.read()
    gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=5, minSize=(100, 100), flags=cv2.CASCADE_SCALE_IMAGE)
    for(x,y,w,h) in faces:
        nbr_predicted, conf = recognizer.predict(gray[y:y+h,x:x+w])
        print(round(100 - conf, 2))
        cv2.rectangle(im,(x-50,y-50),(x+w+50,y+h+50),(225,0,0),2)
        label = face_dict[nbr_predicted]
        if(round(100 - conf, 2)>20):
            cv2.putText(im,str(label),(x,y+h),cv2.FONT_HERSHEY_SIMPLEX, 1,(255,255,255),2)
#           detect = 1   
        else :
            cv2.putText(im,str("UNKNOWN"),(x,y+h),cv2.FONT_HERSHEY_SIMPLEX, 1,(255,255,255),2)
            detect = 0
        cv2.putText(im,"press esc to exit",(x-45,y-40),cv2.FONT_HERSHEY_SIMPLEX, 0.5,(255,255,0),2)
#         if pre_detect != detect:
#             aio.send('foo',detect)
#             pre_detect = detect
    cv2.imshow('im',im)
    k = cv2.waitKey(1) & 0xff
    if k == 27:
        break
cam.release()
cv2.destroyAllWindows()

26.45
36.96
42.84
43.28
45.84
48.0
47.17
45.77
48.59
48.04
49.52
51.17
50.65
50.16
50.72
50.24
52.06
51.94
49.14
50.98
51.44
52.21
50.25
50.99
44.99
44.5
44.76
42.97
42.47
43.49
43.69
45.09
47.14
52.7
53.61
53.09
49.57
49.71
48.51
43.75
44.9
45.93
43.12
46.45
43.07
53.54
53.46
54.19
53.53
52.44
53.37
52.1
49.16
51.63
53.12
55.19
53.73
52.69
54.62
54.72
54.95
55.36
53.72
54.48
53.77
54.35
54.44
53.03
55.35
52.56
48.54
49.0
50.3
54.18
50.61
53.0
51.8
53.16
52.89
52.35
52.6
53.22
52.48
52.62
52.7
54.06
53.1
50.88
52.55
52.9
51.23
53.86


In [ ]:
k = cv2.waitKey(1) & 0xff
    if k == 27:
        break
    elif k == 100:
        displayDb()